### ISSUE TITLE
Some filters start with wp_query_toute_

### ISSUE THREAD

**Issue by samikeijonen** [aucor/wp_query-route-to-rest-api#5]
Some filters start with `wp_query_toute_`, notice the **t**. Not a big issue but might be confusing. Maybe add new filter starting with `wp_query_route_` but keeping the old with backward compability.

**Comment by TeemuSuoranta** [comment]
Sure, could release a minor update where this would be taken care of. The plugin was written pretty much in 1-2 days so it's strange that it is even as coherent as is.

**Comment by TeemuSuoranta** [comment]
Fixed in 1.3.0 release. Finally.
