### ISSUE TITLE
Docs could mention @wordpress/url and addQueryArgs

### ISSUE THREAD

**Issue by samikeijonen** [aucor/wp_query-route-to-rest-api#6]
WP has nice packages like [@wordpress/url](https://github.com/WordPress/gutenberg/tree/master/packages/url). 

Perhaps docs could mention that you can use functions from there, like `addQueryArgs` or `buildQueryString`.

```js
// Import from WP package.
import { addQueryArgs } from '@wordpress/url';

// Use in JS.
var args = {
  'post_type': 'post',
  'orderby': 'title',
  'order': 'ASC'
};

const endpointURL = addQueryArgs( '/wp-json/wp_query/args/', args );
```

**Comment by TeemuSuoranta** [comment]
Good idea. JS examples should be refactored a little anyways as jQuery maybe shouldn't be the number one example anymore.
