### ISSUE TITLE
Possibility to render markup HTML

### ISSUE THREAD

**Issue by samikeijonen** [aucor/wp_query-route-to-rest-api#7]
Sometimes it makes sense that REST API returns markup (HTML) for you. In that case you could use `get_template_part` or similar function to output markup. And then in the JS there is no need to replicate the markup.

Raw example:

```php
// Use to be $data = array();
$data = array(
        'html' => false,
        'messages' => array(
        'empty' => esc_html__( 'No results found', 'textdomain' ),
    ),
);

// Later inside $wp_query loop.

// Extra safety check for unallowed posts
if ( $this->check_is_post_allowed( $wp_query->post ) ) {
    if ( ! empty( $wp_query->posts ) ) {
        $html = '';

        ob_start();

        foreach ( $wp_query->posts as $the_post ) {
            get_template_part( 'partials/card' );
        }

        $html .= ob_get_clean();

        $data['html'] = $html;

        wp_reset_postdata();
    }
}
```

Not sure if that makes sense. Or which kind of hooks would allow this.

**Comment by TeemuSuoranta** [comment]
There are should be some core filters around here https://github.com/aucor/wp_query-route-to-rest-api/blob/master/wp_query-route-to-rest-api.php#L267 as this plugin uses core's stuff for handling post items. Can you work through those or have ideas how this plugin could help?
